version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python train.py  # Train model

  post_build:
    commands:
      - python test.py  # Run test
      - aws s3 cp trained_model.pkl s3://ml-models-bucket/model/  # Upload model to S3
